#
spring:
  jpa:
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: data-sync-app/src/main/resources/sql/create.sql
              create-source: metadata
