#
com:
  github:
    zybercik00:
      excelResource: Chemical treatment process.xlsx
      sheetName: process data

spring:
  datasource:
    url: jdbc:h2:file:./data/DataSyncExcel
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
