@startuml
hide empty members

class MaterialControl <<control>>
class MaterialForm <<boundary>> {
- searchName
- searchBatch
}

class Employee <<actor>>

class Material <<entity>>

class ExcelData <<boundary>>


Employee -down- MaterialForm : uses >
MaterialForm -down- MaterialControl : invoke >
MaterialControl -down- Material : search >
MaterialControl - ExcelData : use >

@enduml