@startuml
'https://plantuml.com/use-case-diagram

actor Employee
boundary "Material Form" as MaterialForm
control "Material Control" as MaterialControl
entity Material
boundary "Data in Excel Files" as ExcelData

Employee -> MaterialForm : remove material
MaterialForm -> MaterialControl : subtract material
MaterialControl -> Material : subtractMaterial

@enduml